### ISSUE TITLE
[Suggestion] Key Combos/Amecs Integration or Features

### ISSUE THREAD

**Issue by greensad** [Einjerjar/keymap#14]
Would be really great to use multiple modifier keys, mapping all Xaero's Minimap keys to a single key using modifiers is extremely convenient and helps to relegate learning multiple binds to a single key. Also for players with smaller boards it can be a boon, I have a 60% board and I simply don't have enough keys to map every bind to a key, however with modifiers I'm able to easily map each handily with keys to spare and keep track of each bind far more easily.

**Comment by Einjerjar** [comment]
Hey there, thanks for the input!, considering the fact that Minecraft allows checking if a modifier is held at a certain point in time, this should very much be possible, I will try to look into implementing as soon as I have free time!

**Comment by Einjerjar** [comment]
This has been covered by the 0.6.0 release via key combinations! :D

- Although, unlike malilib which allows any arbitrary key combination, this only supports modifiers, eg; ctrl+a, alt+shift+x
