### ISSUE TITLE
[Layout Request] Dvorak US Layout

### ISSUE THREAD

**Issue by bryanbecker** [Einjerjar/keymap#18]
**What is the language/locale code for the layout you want to add**
en_us

**Is there an existing variation of the layout you want to add**
en_us is probably closest

**Please provide an image of the layout, preferably the full standard layout for the language**
![image](https://user-images.githubusercontent.com/469798/177005510-1b80f034-c3ac-48e5-a73c-633a38d3de0e.png)

**Anything else you want us to keep in mind while working on the layout**
The layout can be found here: https://en.wikipedia.org/wiki/Dvorak_keyboard_layout

**Comment by Einjerjar** [comment]
Thanks for the heads up!, this will be added onto the next update!

**Comment by Einjerjar** [comment]
This has been covered by the 0.6.0 release! :D

**Comment by bryanbecker** [comment]
Thanks! Works perfect (=

Just FYI, you use a different naming convention for colemak and dvorak layouts -- not sure if it warrants solving, though

**Comment by Einjerjar** [comment]
oh yeah, thanks for that!, should be fixed on the next build :)
