### ISSUE TITLE
[Layout Request] English Colemak

### ISSUE THREAD

**Issue by ghost** [Einjerjar/keymap#19]
en_us

N/A

[
![image](https://user-images.githubusercontent.com/62858980/177197660-df08994d-6637-43b7-a325-9c2ab76e4d5d.png)
](url)

Layout can be found here: [https://colemak.com/](url)

**Comment by Einjerjar** [comment]
Will be on the next update, thanks!

**Comment by Einjerjar** [comment]
This has been covered by the 0.6.0 release! :D
