### ISSUE TITLE
dragging the scroll bar is unexpectedly slow

### ISSUE THREAD

**Issue by JumperREDACTED** [Einjerjar/keymap#2]
https://youtu.be/VhIm-63k2sI

**Comment by Einjerjar** [comment]
Math doesn't still doesnt check out in my head so I'm leaving it as is for now but will try to work it out for the next update, thanks!

**Comment by Einjerjar** [comment]
Fixed on latest commit (kinda)~, will be included in the next build (0.3.2 beta 3 and up)
