### ISSUE TITLE
[Layout Request] Mapping for Mouse Thumb Buttons (Forward & Back)

### ISSUE THREAD

**Issue by ardissaps** [Einjerjar/keymap#21]
Please support mouse button forward and backward button to be used as stand alone + modifer.
Example :

Enlarge mini map press = Alt + Thumb Backward
Hide mini map press = Alt + Thumb Forward
![image](https://user-images.githubusercontent.com/82106625/177330841-29692cb1-de62-49e4-825e-fa5459a5a34f.png)

Currently I still relly on Amec for this, most button already using KeyMap mods.

**Comment by ardissaps** [comment]
It this currently if try to be assigned does not work, it assign regular mouseclick instead. So currently, I need to go to Vanilla(amec) screen to map them (those mouse extra button).

**Comment by Einjerjar** [comment]
Thanks for the heads up! this will be on the next update :)
