### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [Einjerjar/keymap#22]
Forges 41.0.64+ and 41.0.94+ introduce breaking changes for keymap-0.6.0-beta.0+1.19-forge.

**Comment by Einjerjar** [comment]
Hey there, thanks for the heads up!, that is indeed quite an issue, I will try and look into it as soon as I find the time, thanks.

**Comment by Einjerjar** [comment]
Took me long enough xDD, but I think this should be kinda covered now on the latest cf/modrinth(waiting approval), kinda, tho only tested against 1.19.2, not 1.19 and 1.19.1, cuz lazy

**Comment by Baggytrousers27** [comment]
Cheers for all your work on these doovers.
[Take it easy dude.](https://i.kym-cdn.com/photos/images/original/001/628/186/65d.gifv)
[But TAKE IT!](https://i.kym-cdn.com/photos/images/original/001/628/188/bfe.gifv)
