### ISSUE TITLE
[suggestion] Support for mouse side buttons? 

### ISSUE THREAD

**Issue by Celesian** [Einjerjar/keymap#23]
Is it possible for keymap to support mouse 4/5 side buttons?

**Comment by Einjerjar** [comment]
This should already be supported, via the "Other Mouse" button, for space efficiency, only the 3 primary buttons are shown, while the rest are visible when you hover over the "Other Mouse" button

**Comment by Celesian** [comment]
![image](https://user-images.githubusercontent.com/49375840/186015741-343c8a56-a0df-492a-a750-509fa7b3525c.png)
I'm running keymap v[0.4.3-beta.0+1.19-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/keymap/files/3852965) and i don't have the other mouse button

**Comment by Einjerjar** [comment]
ah, that one is the v1 build, the one that supports extra mouse buttons is v2, which is v0.6.0

**Comment by Celesian** [comment]
ah thank you!
