### ISSUE TITLE
zh_cn.json

### ISSUE THREAD

**Issue by DarkCrystalll** [Einjerjar/keymap#26]
{
  "keymap.keyCat": "键盘映射",
  "keymap.keyOpenKeymap": "打开键盘映射",
  "keymap.scrMain": "键盘映射",
  "keymap.scrSettings": "键盘映射设置",
  "keymap.scrLayout": "布局选择",
  "keymap.scrHelp": "帮助",
  "keymap.textHelp": "- 通过按“`”(esc下面的键)打开按键映射屏幕。\n\n-通过“Other Mouse”虚拟键分配额外的鼠标按键，选择要更改的键，然后用所选的鼠标键单击“Other Mouse”按钮。",
  "keymap.lblCredits": "赞助",
  "keymap.catGeneral": "通用",
  "keymap.catLayout": "布局",
  "keymap.catTooltips": "工具提示",
  "keymap.catExtra": "额外",
  "keymap.optFirstOpenDoneExtra": "首次打开完成",
  "keymap.optReplaceKeybindScreen": "更换键盘屏幕",
  "keymap.optMalilibSupport": "Malilib支持",
  "keymap.optShowHelpTooltips": "显示工具提示帮助",
  "keymap.optDebug": "调试1",
  "keymap.optDebug2": "调试2",
  "keymap.optAutoSelectLayout": "从语言自动布局",
  "keymap.optCustomLayout": "布局覆盖",
  "keymap.listCatAll": "所有",
  "keymap.btnSave": "保存",
  "keymap.btnCancel": "取消",
  "keymap.btnReset": "重置",
  "keymap.btnResetTip": "将当前选定的项目重置为其默认值。",
  "keymap.btnResetAll": "全部重置",
  "keymap.btnResetAllTip": "将所有键绑定重置为其默认值。",
  "keymap.btnOpenSettings": "⚙ 设置",
  "keymap.btnOpenSettingsTip": "打开设置屏幕",
  "keymap.btnOpenLayouts": "☰布局",
  "keymap.btnOpenLayoutsTip": "打开布局选择屏幕",
  "keymap.btnOpenHelp": "? 帮助",
  "keymap.btnOpenHelpTip": "一些有用的信息",
  "keymap.btnClearSearch": "❌",
  "keymap.btnClearSearchTip": "清除当前搜索输入",
  "keymap.btnClearSearchTip2": "关闭此屏幕",
  "keymap.inpSearchPlaceholder": "搜索",
  "keymap.dummy": "",
  "keymap.dummy2": "上面的行只是为了让我通过复制快速创建行，因为我那么懒惰，这一行在这里，所以我仍然可以在上面的行上有一个逗号......想来想去，我在这里写这个随机描述，是不是让我不那么懒惰了？:D"
}

**Comment by DarkCrystalll** [comment]
Very great mod!  hope author can compatible more Chinese input

**Comment by Mccandycube6623** [comment]
你好

**Comment by DarkCrystalll** [comment]
> 你好

你好

**Comment by Einjerjar** [comment]
Thanks for this! will add this to the next release!

**Comment by DarkCrystalll** [comment]
!!!  :D
