### ISSUE TITLE
[Suggestion] Clicking a key should let you edit the keybinds bound to it

### ISSUE THREAD

**Issue by JumperREDACTED** [Einjerjar/keymap#3]
clicking one of these
![image](https://user-images.githubusercontent.com/83337894/161448669-761d575d-dc0b-426b-88b0-2dfd635b28d0.png)

would bring up all the keybinds bound to that key here
![image](https://user-images.githubusercontent.com/83337894/161448687-132cc0c7-720e-4650-a5cf-bfa90e64538b.png)

**Comment by Einjerjar** [comment]
I think thats a great idea, might push it into the next update, thanks!
