### ISSUE TITLE
Chinese search

### ISSUE THREAD

**Issue by Holy-Fak** [Einjerjar/keymap#38]
If use chinese search key that will get nothing, 
and click from category list will get nothing if there are chinese word

**Comment by qznfbnj** [comment]
## Chinese search
I can search with 0.7.0-beta.0+1.19.2-forge.
![image](https://user-images.githubusercontent.com/100760086/228247044-8ea7451f-72ee-41e8-ac43-8b52ec9887ed.png)

## Category mode
Looks like it doesn't recognize Chinese characters on category search mode.
![image](https://user-images.githubusercontent.com/100760086/228245578-dd4a57a6-3f41-423b-895d-6add81047aa4.png)

## Another mod: Keyboard Wizard
It can find by category but it has no other keyboard sections like numpads
![image](https://user-images.githubusercontent.com/100760086/228256679-690566e0-e675-4602-9bc0-9ffe35d1706f.png)

**Comment by Holy-Fak** [comment]
thanks for supplement, and here is more detail:

version: keymap-0.7.0-beta.1+1.18.2-fabric.jar


 click it like this:
![image](https://user-images.githubusercontent.com/63405709/228439404-b6d0fbbc-5d06-443a-98d9-752ce31b8e2f.png)


When i type in exacttly like this below:
![image](https://user-images.githubusercontent.com/63405709/228439029-088f264a-da1d-459a-bc5d-7a6c2e7359cd.png)

**Comment by Einjerjar** [comment]
Looks like this was covered by SettingDust over at https://github.com/Einjerjar/keymap/pull/45 (big thanks!), I'll try and publish build as soon as possible, thanks!
