### ISSUE TITLE
Malilib issue - MiniHUD keybinds don't show up at all

### ISSUE THREAD

**Issue by JumperREDACTED** [Einjerjar/keymap#4]
MiniHUD 0.21.5
Malilib 0.11.8
Keymap 0.3.0-beta.3+1.18.1
https://mclo.gs/sI3wVJa

I can see Litematica and Tweakeroo keybinds, but not MiniHUD.

**Comment by Einjerjar** [comment]
thanks for this one, also found the issue while using tweakeroo, mb I didn'r look into the issues much earlier, this has been fixed in the latest update :)

**Comment by Einjerjar** [comment]
Just realized that minihud does display "some" keybind but not all, thanks again for the heads up, will work on this now.

**Comment by Einjerjar** [comment]
latest commits should've fixed this, thanks for the heads up!

**Comment by Einjerjar** [comment]
latest commits should've fixed this, thanks for the heads up! (and yeah, it was def my fault, lol)
