### ISSUE TITLE
Not saving my keymap changes.

### ISSUE THREAD

**Issue by Zoofule** [Einjerjar/keymap#42]
For some reason, after messing around with the mod and adjusting a few keys, it stops saving any keys I try to remap.

In the console, this is what the log says

> [07/05/2023 04:50:04 AM] [Render thread/WARN] KeyComboData(keyCode=66, keyType=KEYBOARD, alt=false, shift=false, ctrl=false)
> [07/05/2023 04:50:07 AM] [Render thread/WARN] KeyComboData(keyCode=80, keyType=KEYBOARD, alt=false, shift=false, ctrl=false)
> [07/05/2023 04:50:07 AM] [Render thread/WARN] Remove ignored, Keymapping [gui.xaero_new_waypoint] not registered!

Minecraft: 1.19.2
Forge: 43.2.0
Mod Version: keymap-0.7.0-beta.0+1.19.2-forge

Let me know if there is any other information I can provide to help solve this issue. I have been playing modded Minecraft for years and I had always used controlling in the past, but this mod is an absolute game changer, and would love to help ensure that this becomes the new standard mod for keymapping.

**Comment by Einjerjar** [comment]
Apologies for the lack of response, I'll look into this, thanks!

**Comment by SettingDust** [comment]
should be fixed by the PR I think. need your test @Zoofule

**Comment by Zoofule** [comment]
> should be fixed by the PR I think. need your test @Zoofule 

Ok, I'll try to test it soon, unfortunately my summer has gotten extremely busy.

**Comment by Zoofule** [comment]
> Apologies for the lack of response, I'll look into this, thanks!

No worries, everyone has different things in life that make availability fluctuate.

**Comment by Einjerjar** [comment]
Thanks @SettingDust and @Zoofule!, the build should be up on curseforge for now, forgot to update modrinth, gimme a sec, 

ps: forgot that I only built for 1.19.2 and 1.18.2, hopefully there wont be any issues

**Comment by Einjerjar** [comment]
Aaand I completely forgot about uploading it to Modrinth, haha, in any case, it up now, thanks!,

oh, also, there's also this for bleeding edge builds, just in case https://app.circleci.com/pipelines/github/Einjerjar/keymap
