### ISSUE TITLE
1.18.2 keymaps not changing

### ISSUE THREAD

**Issue by Dabbpool** [Einjerjar/keymap#43]
in the newest version of 1.18.2 the keymaps are saved on the menu but not actually being changed

**Comment by Dabbpool** [comment]
it was this in my folder keybind_fix-1.0.0 it works in 1.19.2 but i had to back up for a server mod anyway i hope this helps you or anyone in the future and thanks for this amazing mod i totally couldn't go on redoing everything correctly without it

**Comment by Einjerjar** [comment]
Apologies for the lack of response, thanks for that info! I'll probably look into adding a FAQ page or something and add this into that, thanks!
