### ISSUE TITLE
Long keybind names get cut off

### ISSUE THREAD

**Issue by JumperREDACTED** [Einjerjar/keymap#5]
![image](https://user-images.githubusercontent.com/83337894/162031975-3966c453-0d1a-46b3-b65c-75785434388a.png)

**Comment by Einjerjar** [comment]
This is intended behaviour, as the text would end up overflowing to the side (which looks terrible xD), instead, you can hover over the item to get a tooltip with the full keybind name and its bindings

**Comment by JumperREDACTED** [comment]
Makes sense, one idea i had was to make them scroll but mouseovering works just fine if not better
