### ISSUE TITLE
Could u fix textboxes overlapping?

### ISSUE THREAD

**Issue by HacoKavanah** [Einjerjar/keymap#6]
![image](https://user-images.githubusercontent.com/87395651/162141425-333e98ab-6390-4cbc-91e2-40d5e60dcf80.png)

**Comment by Einjerjar** [comment]
Looks like i forgot to clip the text from the category list, ill work on it tonight, thanks for the heads up!

**Comment by Einjerjar** [comment]
Fixed on latest build~
